customhost = "employee.crtqicsjgoxm.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "foozhihsing-employee"
customregion = "us-east-1"
